export const FETCH_NOTIFICATION_REQUEST = "notification/FETCH_NOTIFICATION_REQUEST";
export const FETCH_NOTIFICATION_SUCCESS = "notification/FETCH_NOTIFICATION_SUCCESS";
export const FETCH_NOTIFICATION_FAILURE = "notification/FETCH_NOTIFICATION_FAILURE";

export const RECEIVE_NOTIFICATION_COUNT = "notification/RECEIVE_NOTIFICATION_COUNT";