export const FETCH_NOTIFICATION_REQUEST = "notification/FETCH_NOTIFICATION_REQUEST";
export const FETCH_NOTIFICATION_SUCCESS = "notification/FETCH_NOTIFICATION_SUCCESS";
export const FETCH_NOTIFICATION_FAILURE = "notification/FETCH_NOTIFICATION_FAILURE";