export const BUG_FETCH_REQUEST = "bug/BUG_FETCH_REQUEST";
export const BUG_FETCH_SUCCESS = "bug/BUG_FETCH_SUCCESS";
export const BUG_FETCH_FAILURE = "bug/BUG_FETCH_FAILURE";

export const ADD_MEMBER_REQUEST = "bug/ADD_MEMBER_REQUEST";
export const ADD_MEMBER_SUCCESS = "bug/ADD_MEMBER_SUCCESS";
export const ADD_MEMBER_FAILURE = "bug/ADD_MEMBER_FAILURE";

export const UPDATE_BUG_BODY_REQUEST = "bug/UPDATE_BUG_BODY_REQUEST";
export const UPDATE_BUG_BODY_SUCCESS = "bug/UPDATE_BUG_BODY_SUCCESS";
export const UPDATE_BUG_BODY_FAILURE = "bug/UPDATE_BUG_BODY_FAILURE";

export const POST_BUG_COMMENT_REQUEST = "bug/POST_BUG_COMMENT_REQUEST";
export const POST_BUG_COMMENT_SUCCESS = "bug/POST_BUG_COMMENT_SUCCESS";
export const POST_BUG_COMMENT_FAILURE = "bug/POST_BUG_COMMENT_FAILURE";

export const UPDATE_LABEL_REQUEST = "bug/UPDATE_LABEL_REQUEST";
export const UPDATE_LABEL_SUCCESS = "bug/UPDATE_LABEL_SUCCESS";
export const UPDATE_LABEL_FAILURE = "bug/UPDATE_LABEL_FAILURE";

export const DELETE_COMMENT_REQUEST = "bug/DELETE_COMMENT_REQUEST";
export const DELETE_COMMENT_SUCCESS = "bug/DELETE_COMMENT_SUCCESS";
export const DELETE_COMMENT_FAILURE = "bug/DELETE_COMMENT_FAILURE";

export const CLOSE_BUG_REQUEST = "bug/CLOSE_BUG_REQUEST";
export const CLOSE_BUG_SUCCESS = "bug/CLOSE_BUG_SUCCESS";
export const CLOSE_BUG_FAILURE = "bug/CLOSE_BUG_FAILURE";

export const REMOVE_MEMBER_REQUEST = "bug/REMOVE_MEMBER_REQUEST";
export const REMOVE_MEMBER_SUCCESS = "bug/REMOVE_MEMBER_SUCCESS";
export const REMOVE_MEMBER_FAILURE = "bug/REMOVE_MEMBER_FAILURE";

export const UPDATE_REACTIONS = "bug/UPDATE_REACTIONS";