export const BUG_FETCH_REQUEST = "bug/BUG_FETCH_REQUEST";
export const BUG_FETCH_SUCCESS = "bug/BUG_FETCH_SUCCESS";
export const BUG_FETCH_FAILURE = "bug/BUG_FETCH_FAILURE";

export const ADD_MEMBER_REQUEST = "bug/ADD_MEMBER_REQUEST";
export const ADD_MEMBER_SUCCESS = "bug/ADD_MEMBER_SUCCESS";
export const ADD_MEMBER_FAILURE = "bug/ADD_MEMBER_FAILURE";
