export const FETCH_PROJECT_REQUEST = "project/FETCH_PROJECT_REQUEST";
export const FETCH_PROJECT_SUCCESS = "project/FETCH_PROJECT_SUCCESS";
export const FETCH_PROJECT_FAILURE = "project/FETCH_PROJECT_FAILURE";

export const ADD_PROJECT_REQUEST = "project/ADD_PROJECT_REQUEST";
export const ADD_PROJECT_SUCCESS = "project/ADD_PROJECT_SUCCESS";
export const ADD_PROJECT_FAILURE = "project/ADD_PROJECT_FAILURE";