export const FETCH_SELECT_PROJECT_REQUEST = "project/FETCH_SELECT_PROJECT_REQUEST"
export const FETCH_SELECT_PROJECT_SUCCESS = "project/FETCH_SELECT_PROJECT_SUCCESS"
export const FETCH_SELECT_PROJECT_FAILURE = "project/FETCH_SELECT_PROJECT_FAILURE"

export const ADD_MEMBER_REQUEST = "project/ADD_MEMBER_REQUEST";
export const ADD_MEMBER_SUCCESS = "project/ADD_MEMBER_SUCCESS";
export const ADD_MEMBER_FAILURE = "project/ADD_MEMBER_FAILURE";

export const REMOVE_MEMBER_REQUEST = "project/REMOVE_MEMBER_REQUEST";
export const REMOVE_MEMBER_SUCCESS = "project/REMOVE_MEMBER_SUCCESS";
export const REMOVE_MEMBER_FAILURE = "project/REMOVE_MEMBER_FAILURE";
