export const FETCH_SELECT_PROJECT_REQUEST = "project/FETCH_SELECT_PROJECT_REQUEST"
export const FETCH_SELECT_PROJECT_SUCCESS = "project/FETCH_SELECT_PROJECT_SUCCESS"
export const FETCH_SELECT_PROJECT_FAILURE = "project/FETCH_SELECT_PROJECT_FAILURE"